<!DOCTYPE html>
<html lang="en-us">
<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="theme" content="hugo-academic">
  <meta name="generator" content="Hugo 0.31.1" />
  <meta name="author" content="Sau-Chin Chen">
  <meta name="description" content="Assistant Professor of Cognitive Psychology">

  
  <link rel="alternate" hreflang="en-us" href="http://scchen.me/en/post/2016-04-30-autopsy-of-nhst-and-bayesian-models/">

  
  


  

  
  
  
  
    
  
  
  
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha512-6MXa8B6uaO18Hid6blRMetEIoPqHf7Ux1tnyIQdpt9qI5OACx7C+O3IVTr98vwGnlcg0LOLa02i9Y1HpVhlfiw==" crossorigin="anonymous">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/academicons/1.8.1/css/academicons.min.css" integrity="sha512-NThgw3XKQ1absAahW6to7Ey42uycrVvfNfyjqcFNgCmOCQ5AR4AO0SiXrN+8ZtYeappp56lk1WtvjVmEa+VR6A==" crossorigin="anonymous">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" integrity="sha512-SfTiTlX6kk+qitfevl/7LibUOeJWlt9rbyDn92a1DqWOw9vWG2MFoays0sgObmWazO5BQPiFucnnEAjpAB+/Sw==" crossorigin="anonymous">
  
  
  
  
  <link rel="stylesheet" href="//fonts.googleapis.com/css?family=Lato:400,700%7cMerriweather%7cRoboto&#43;Mono">
  
  <link rel="stylesheet" href="/en/styles.css">
  

  

  
  <link rel="alternate" href="http://scchen.me/index.xml" type="application/rss+xml" title="Sau-Chin Chen&#39;s Website">
  <link rel="feed" href="http://scchen.me/index.xml" type="application/rss+xml" title="Sau-Chin Chen&#39;s Website">
  

  <link rel="manifest" href="/site.webmanifest">
  <link rel="icon" type="image/png" href="/img/icon.png">
  <link rel="apple-touch-icon" type="image/png" href="/img/icon-192.png">

  <link rel="canonical" href="http://scchen.me/en/post/2016-04-30-autopsy-of-nhst-and-bayesian-models/">

  <meta property="twitter:card" content="summary_large_image">
  
  <meta property="twitter:site" content="@SauChin_Chen">
  <meta property="twitter:creator" content="@SauChin_Chen">
  
  <meta property="og:site_name" content="Sau-Chin Chen&#39;s Website">
  <meta property="og:url" content="http://scchen.me/en/post/2016-04-30-autopsy-of-nhst-and-bayesian-models/">
  <meta property="og:title" content="Autopsy of NHST and Bayesian Models (part 1) | Sau-Chin Chen&#39;s Website">
  <meta property="og:description" content="">
  <meta property="og:locale" content="en-us">
  
  <meta property="article:published_time" content="2016-04-30T00:00:00&#43;00:00">
  
  <meta property="article:modified_time" content="2016-04-30T00:00:00&#43;00:00">
  

  

  <title>Autopsy of NHST and Bayesian Models (part 1) | Sau-Chin Chen&#39;s Website</title>

</head>
<body id="top" data-spy="scroll" data-target="#toc" data-offset="71" >

<nav class="navbar navbar-default navbar-fixed-top" id="navbar-main">
  <div class="container">

    
    <div class="navbar-header">
      
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
              data-target=".navbar-collapse" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      
      <a class="navbar-brand" href="/en/">Sau-Chin Chen&#39;s Website</a>
    </div>

    
    <div class="collapse navbar-collapse">

      
      
      <ul class="nav navbar-nav navbar-right">
        

        

        
          
        

        <li class="nav-item">
          <a href="/en/#about">
            
            <span>Home</span>
            
          </a>
        </li>

        
        

        

        
          
        

        <li class="nav-item">
          <a href="/en/#publications_selected">
            
            <span>Publications</span>
            
          </a>
        </li>

        
        

        

        
          
        

        <li class="nav-item">
          <a href="/en/#projects">
            
            <span>Projects</span>
            
          </a>
        </li>

        
        

        

        
          
        

        <li class="nav-item">
          <a href="/en/#posts">
            
            <span>Posts</span>
            
          </a>
        </li>

        
        
      

      
      </ul>

    </div>
  </div>
</nav>


<article class="article" itemscope itemtype="http://schema.org/Article">

  


  <div class="article-container">
    <div class="article-inner">
      <h1 itemprop="name">Autopsy of NHST and Bayesian Models (part 1)</h1>

      

<div class="article-metadata">

  <span class="article-date">
    
    <time datetime="2016-04-30 00:00:00 &#43;0000 UTC" itemprop="datePublished">
      Sat, Apr 30, 2016
    </time>
  </span>

  

  
  
  <span class="middot-divider"></span>
  <a href="http://scchen.me/en/post/2016-04-30-autopsy-of-nhst-and-bayesian-models/#disqus_thread"></a>
  

  
  
  
  <span class="middot-divider"></span>
  <span class="article-categories">
    <i class="fa fa-folder"></i>
    
    <a href="/en/categories/practices">Practices</a
    >
    
  </span>
  
  

  
  
<div class="share-box" aria-hidden="true">
  <ul class="share">
    <li>
      <a class="twitter"
         href="https://twitter.com/intent/tweet?text=Autopsy%20of%20NHST%20and%20Bayesian%20Models%20%28part%201%29&amp;url=http%3a%2f%2fscchen.me%2fen%2fpost%2f2016-04-30-autopsy-of-nhst-and-bayesian-models%2f"
         target="_blank" rel="noopener">
        <i class="fa fa-twitter"></i>
      </a>
    </li>
    <li>
      <a class="facebook"
         href="https://www.facebook.com/sharer.php?u=http%3a%2f%2fscchen.me%2fen%2fpost%2f2016-04-30-autopsy-of-nhst-and-bayesian-models%2f"
         target="_blank" rel="noopener">
        <i class="fa fa-facebook"></i>
      </a>
    </li>
    <li>
      <a class="email"
         href="mailto:?subject=Autopsy%20of%20NHST%20and%20Bayesian%20Models%20%28part%201%29&amp;body=http%3a%2f%2fscchen.me%2fen%2fpost%2f2016-04-30-autopsy-of-nhst-and-bayesian-models%2f">
        <i class="fa fa-envelope"></i>
      </a>
    </li>
  </ul>
</div>


  

</div>


      <div class="article-style" itemprop="articleBody">
        <p>Chapter 2 of <a href="http://xcelab.net/rm/statistical-rethinking/">Statistical Rethinking: A Bayesian Course with Examples in R and Stan</a> introduces a water tossing example for the demonstration how Bayesain model run through the data based on the researcher’s hypothesis. This chapter defines a three stage process that are used in the coming chapters. We start from a narrated <strong>Data Story</strong>, then <strong>update</strong> the models by filling data in, and finally <strong>evaluate</strong> all the <strong>upated</strong> models. This literated process shows a clear picture for the learners who have yet stuied statistics before read this book. The readers who have studied statistics, like me, will have a hole in the mind what are the differences between Bayesian methods and the null hypothesis significance testing (NHST) in this process. After read Michael Clark’s <a href="https://sites.google.com/a/umich.edu/micl/miscfiles/IntroBayes.pdf">Bayesian Basics: A Conceptual Introduction with Application in R and Stan</a> on <a href="http://mc-stan.org/documentation/">Stan official site</a>, I require the key to understand the difference between the two golems.</p>
<p>The critical difference is which type of <strong>conditional probability</strong> the statistical method is used to evaluate the model. Once we collected the data based on some hypothesis, we have the distribution of hypothesis $ p( ) $ and the distribution of data $ p(y) $. NHST compuates the probability we have the data when the hypothesis is true $ p(y|) $. In practical, <em>p</em> value refers to the <strong>conditional probability</strong> of the null hypothesis, and * confidence interval* suggests a range of plausible outcomes based on the <em>confiditional probability</em> of the real hypothesis. A Bayesian method compuates the probability the hypothesis is approved based on the data we have $ p(|y) $. Because the computation of $ p(|y) $ needs the likelihood $ p(y|) $ and the priori $ p() $, of course a Baysian method cost more steps than NHST.</p>
<p>$ $ has a term <strong>parameter</strong> in many statstical textbooks. It is a space of numbers that provides the axis where the above probability distribution sit on. <strong>Likelihood</strong> is the <strong>sampling distribution</strong> we have to update before we run NHST. As like I show in <a href="/blog/2016/03/learning-sampling-distribution-in-r-programming.html">Learning Sampling Distribution in R Programming</a>, a sampling distribution will approach one $ $ with the increasing sample size. Sample size is the key for NHST because it could change the evaluation criteron on the statistical model.</p>
<p>Here is a pseudo experiment I want to know if a test is success based on the expect value smaller than 5 (Obersvations are 1, 2, 3, 4, 5, 6, 7, 8, 9, 10). I completed an experiment of 25 observations and an experiment 36 observations. In use of NHST with a critical value (p &lt; .05), the criterion change with the sample size. The simulation</p>
<pre class="r"><code>set.seed(1)
OBV &lt;- 1:10
Dist25 &lt;- NULL
Dist36 &lt;- NULL
count = 100
while(count &gt; 0){Dist25 &lt;- c(Dist25,mean(sample(OBV, 25,replace = TRUE) ) ); count &lt;- count - 1}
Dist25_Density &lt;- data.frame(Theta = density(Dist25, kernel = &quot;gaussian&quot;)$x, Density = density(Dist25, kernel = &quot;gaussian&quot;)$y)
CL25 &lt;- max(Dist25_Density$Theta[Dist25_Density$Theta &lt; 5 &amp; Dist25_Density$Density &lt; .05])
print(CL25)  ## The smallest parameter that could make judgement</code></pre>
<pre><code>## [1] 4.152939</code></pre>
<pre class="r"><code>count = 100
while(count &gt; 0){Dist36 &lt;- c(Dist36,mean(sample(OBV, 36,replace = TRUE) ) ); count &lt;- count - 1}
Dist36_Density &lt;- data.frame(Theta = density(Dist36, kernel = &quot;gaussian&quot;)$x, Density = density(Dist36, kernel = &quot;gaussian&quot;)$y)
CL36 &lt;- max(Dist36_Density$Theta[Dist36_Density$Theta &lt; 5 &amp; Dist36_Density$Density &lt; .05])
print(CL36)  ## The smallest parameter that could make judgement</code></pre>
<pre><code>## [1] 4.41705</code></pre>
<p>When this experiment outputs a avarage value between 4.15 and 4.42, would you like to collect the data more than 36 participants? This is the opportunity many researchers have to struggle in their study. Researchers who are educated as like me used to collect the observation till the <em>p</em> value is smaller than .05. Most researchers used to stop the experiment till the 36th participant finished the experiment. However, this treatment lacks of the serious scientific thinking. If the hypothesis has set up the conditions to have the average, the sample size should be appointed before the start of experiment.</p>
<p>The appointment of sample size could be loose when the possible average is uncertain. When the experiment is conducted at first time in the world, NHST without the appointment of sample size could draw the range of averages that might obey the hypothesis. On the other hand, the following studies better has the appointment of sample size. In this case, NHST has to accompany the other statistical evaluation, such as power, effect size, to find the appropriate sample size. Therefore, NHST will perform well when the researcher conducted the first study or have the preparation as well as the first study. This will be the key in my autopsy of Bayesian method.</p>

      </div>

      


<div class="article-tags">
  
  <a class="btn btn-primary btn-outline" href="/en/tags/bayesian">Bayesian</a>
  
  <a class="btn btn-primary btn-outline" href="/en/tags/rethinking">Rethinking</a>
  
  <a class="btn btn-primary btn-outline" href="/en/tags/statistics">statistics</a>
  
</div>



    </div>
  </div>

</article>



<div class="article-container article-widget">
  <div class="hr-light"></div>
  <h3>Related</h3>
  <ul>
    
    <li><a href="/en/post/2016-04-22-check-my-tools-to-create-and-manipulate-golems/">Check My Tools to Create and Manipulate Golems</a></li>
    
    <li><a href="/en/post/2016-04-05-display-math-equation-in-post/">Display Math Equation in Post</a></li>
    
    <li><a href="/en/post/2016-04-05-vectors-in-mathematics-and-in-codes/">Vectors in mathematics and in codes</a></li>
    
    <li><a href="/en/post/2016-03-30-learning-sampling-distribution-in-r-programming/">Learning Sampling Distribution in R Programming</a></li>
    
  </ul>
</div>



<div class="container article-widget">
  <nav>
  <ul class="pager">
    
    <li class="previous"><a href="http://scchen.me/en/post/2016-04-22-check-my-tools-to-create-and-manipulate-golems/"><span
      aria-hidden="true">&larr;</span> Check My Tools to Create and Manipulate Golems</a></li>
    

    
    <li class="next"><a href="http://scchen.me/en/post/2016-05-05-rethink-significance/">Rethink Significance <span
      aria-hidden="true">&rarr;</span></a></li>
    
  </ul>
</nav>

</div>


<div class="article-container">
  
<section id="comments">
  <div id="disqus_thread"></div>
<script>
    var disqus_config = function () {
    
    
    
    };
    (function() {
        if (["localhost", "127.0.0.1"].indexOf(window.location.hostname) != -1) {
            document.getElementById('disqus_thread').innerHTML = 'Disqus comments not available by default when the website is previewed locally.';
            return;
        }
        var d = document, s = d.createElement('script'); s.async = true;
        s.src = '//' + "sauchinchen" + '.disqus.com/embed.js';
        s.setAttribute('data-timestamp', +new Date());
        (d.head || d.body).appendChild(s);
    })();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
<a href="https://disqus.com" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a>
</section>


</div>

<footer class="site-footer">
  <div class="container">
    <p class="powered-by">

      &copy; 2017 Sau-Chin Chen &middot; 

      Powered by the
      <a href="https://sourcethemes.com/academic/" target="_blank" rel="noopener">Academic theme</a> for
      <a href="https://gohugo.io" target="_blank" rel="noopener">Hugo</a>.

      <span class="pull-right" aria-hidden="true">
        <a href="#" id="back_to_top">
          <span class="button_icon">
            <i class="fa fa-chevron-up fa-2x"></i>
          </span>
        </a>
      </span>

    </p>
  </div>
</footer>


<div id="modal" class="modal fade" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close btn-large" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Cite</h4>
      </div>
      <div>
        <pre><code class="modal-body tex"></code></pre>
      </div>
      <div class="modal-footer">
        <a class="btn btn-primary btn-outline js-copy-cite" href="#" target="_blank">
          <i class="fa fa-copy"></i> Copy
        </a>
        <a class="btn btn-primary btn-outline js-download-cite" href="#" target="_blank">
          <i class="fa fa-download"></i> Download
        </a>
        <div id="modal-error"></div>
      </div>
    </div>
  </div>
</div>

    

    
    
    <script id="dsq-count-scr" src="//sauchinchen.disqus.com/count.js" async></script>
    

    

    
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js" integrity="sha512-3P8rXCuGJdNZOnUx/03c1jOTnMn3rP63nBip5gOP2qmUh5YAdVAvFZ1E+QLZZbC1rtMrQb+mah3AfYW11RUrWA==" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.imagesloaded/4.1.3/imagesloaded.pkgd.min.js" integrity="sha512-umsR78NN0D23AzgoZ11K7raBD+R6hqKojyBZs1w8WvYlsI+QuKRGBx3LFCwhatzBunCjDuJpDHwxD13sLMbpRA==" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha512-iztkobsvnjKfAtTNdHkGVjAYTrrtlC7mGp/54c40wowO7LhURYl3gVzzcEqGl/qKXQltJ2HwMrdLcNUdo+N/RQ==" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.isotope/3.0.4/isotope.pkgd.min.js" integrity="sha512-VDBOIlDbuC4VWxGJNmuFRQ0Li0SKkDpmGyuhAG5LTDLd/dJ/S0WMVxriR2Y+CyPL5gzjpN4f/6iqWVBJlht0tQ==" crossorigin="anonymous"></script>
    
    
    <script src="/js/hugo-academic.js"></script>
    

    
    

    
    
    <script type="text/x-mathjax-config">
        MathJax.Hub.Config({ tex2jax: { inlineMath: [['$','$'], ['\\(','\\)']] } });
    </script>
    
    <script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-AMS_CHTML" integrity="sha512-tOav5w1OjvsSJzePRtt2uQPFwBoHt1VZcUq8l8nm5284LEKE9FSJBQryzMBzHxY5P0zRdNqEcpLIRVYFNgu1jw==" crossorigin="anonymous"></script>
    
    

  </body>
</html>

